version: 1.0.{build}

configuration: Debug
image: Visual Studio 2017
environment:
  COVERALLS_REPO_TOKEN:
    secure: gjE9iuhHz/Wb2M5QbVBM8gBDqrOxbml+zD+HUXdSf95kFkSxXV+Lu9H5rnILhoG/
before_build:
  - nuget restore
build:
  project: PageLayout.sln
  verbosity: minimal
test_script:
- ps: >-
    .\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:nunit-console.exe "-targetargs:""PageLayoutServiceTests\bin\$env:CONFIGURATION\PageLayoutServiceTests.dll"" /noshadow" -filter:"+[PageLayout*]*" -output:opencoverCoverage.xml
    $coveralls = (Resolve-Path "packages/coveralls.net.*/tools/csmacnz.coveralls.exe").ToString()
    
    $env:APPVEYOR_BUILD_NUMBER
    
    & $coveralls --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --useRelativePaths --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_BUILD_NUMBER --serviceName appveyor